-- Production schema for JFS AI WhatsApp: Customer -> Conversation -> Order -> Automation Job.
-- Apply through Supabase migrations; this file documents the production DDL already applied to JFS AI Platform.
create table if not exists public.jfs_orders (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, contact_id uuid references public.jfs_contacts(id) on delete set null, conversation_id uuid references public.jfs_conversations(id) on delete set null, status text not null default 'pending', total_amount numeric(14,2) not null default 0, currency text not null default 'IDR', source text not null default 'whatsapp', external_id text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jfs_order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.jfs_orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, quantity integer not null check(quantity>0), unit_price numeric(14,2) not null default 0, subtotal numeric(14,2) generated always as (quantity * unit_price) stored);
create table if not exists public.jfs_automation_jobs (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, automation_id uuid references public.jfs_automations(id) on delete set null, contact_id uuid references public.jfs_contacts(id) on delete set null, order_id uuid references public.jfs_orders(id) on delete set null, channel text not null default 'whatsapp', scheduled_at timestamptz not null, payload jsonb not null default '{}'::jsonb, status text not null default 'pending', attempts integer not null default 0, last_error text, sent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists jfs_contacts_tenant_phone_uidx on public.jfs_contacts(tenant_id,phone);
create unique index if not exists jfs_channel_phone_number_id_uidx on public.jfs_channel_connections(channel,((metadata->>'phone_number_id'))) where metadata->>'phone_number_id' is not null;
create index if not exists jfs_automation_jobs_due_idx on public.jfs_automation_jobs(status,scheduled_at);
create index if not exists jfs_orders_tenant_created_idx on public.jfs_orders(tenant_id,created_at desc);
alter table public.jfs_orders enable row level security;
alter table public.jfs_order_items enable row level security;
alter table public.jfs_automation_jobs enable row level security;
create policy jfs_orders_tenant_manage on public.jfs_orders for all to authenticated using (public.jfs_user_can_manage_tenant(tenant_id)) with check (public.jfs_user_can_manage_tenant(tenant_id));
create policy jfs_order_items_tenant_manage on public.jfs_order_items for all to authenticated using (exists(select 1 from public.jfs_orders o where o.id=order_id and public.jfs_user_can_manage_tenant(o.tenant_id))) with check (exists(select 1 from public.jfs_orders o where o.id=order_id and public.jfs_user_can_manage_tenant(o.tenant_id)));
create policy jfs_automation_jobs_tenant_manage on public.jfs_automation_jobs for all to authenticated using (public.jfs_user_can_manage_tenant(tenant_id)) with check (public.jfs_user_can_manage_tenant(tenant_id));
